# This file is auto-generated by hatch-gradle-version. Do not edit.

GRADLE_VERSION = "0.2.0"
FULL_VERSION = "0.2.0.1.0.dev0"

ARCHIVES_BASE_NAME = "manifestation"
FABRIC_KOTLIN_VERSION = "1.10.19+kotlin.1.9.23"
FABRIC_VERSION = "0.92.0+1.20.1"
HEXCASTING_VERSION = "0.11.3"
LOADER_VERSION = "0.15.7"
MAVEN_GROUP = "com.bluup.manifestation"
MINECRAFT_VERSION = "1.20.1"
MOD_VERSION = "0.2.0"
ORG_GRADLE_JVMARGS = "-Xmx2G"
ORG_GRADLE_PARALLEL = "true"
